# Generated by Django 3.2.6 on 2023-05-24 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('sub_total', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Encabezado Pedido',
                'verbose_name_plural': 'Encabezado Pedido',
            },
        ),
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('', 'Seleccione el tipo de solicitud'), ('P', 'Pregunta'), ('Q', 'Queja'), ('R', 'Reclamo')], max_length=1, verbose_name='Tipo de solicitud')),
                ('description', models.TextField(verbose_name='Detalle de la solicitud')),
            ],
            options={
                'verbose_name': 'Pregunta, Queja y Reclamo',
                'verbose_name_plural': 'Preguntas, Quejas y Reclamos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('price', models.FloatField(default=0, verbose_name='Precio')),
                ('size', models.FloatField(max_length=10, verbose_name='Talla')),
                ('color', models.FloatField(max_length=45, unique=True, verbose_name='Color')),
                ('stock', models.IntegerField(default=0, verbose_name='Existencia')),
                ('image', models.ImageField(upload_to='products_pics', verbose_name='Imagén del producto')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='OrderDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.orderheader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.product')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalles Pedido',
            },
        ),
    ]
