# Generated by Django 3.2.6 on 2023-05-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20230531_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=45, verbose_name='Color'),
        ),
    ]
